services:
  backend:
    image: gopinathbca35/mern-stack-backend:latest
    ports:
      - "5050:5050"
    networks:
      - app_network
    environment:
      MONGO_URI: mongodb://mongodb:27017/appdb
    depends_on:
      - mongodb

  frontend:
    image: gopinathbca35/mern-stack-frontend:latest
    ports:
      - "5173:5173"
    networks:
      - app_network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app_network
    volumes:
      - mongo-data:/data/db

networks:
  app_network:
