resources:
  - frontend/frontend-deployment.yaml
  - frontend/frontend-service.yaml

  - backend/backend-deployment.yaml
  - backend/backend-service.yaml

  - mongodb/mongodb-statefulset.yaml
  - mongodb/mongodb-service.yaml

  - ingress/ingress.yaml
